vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            # Rename imageFile created uniquely
            namer: Vich\UploaderBundle\Naming\UniqidNamer
