# Anonymous Routes
home:
  path: /
  controller: App\Controller\HomeController::index

properties:
  path: /property
  controller: App\Controller\PropertyController::index

property:
  path: /property/{id}
  controller: App\Controller\PropertyController::show
  requirements:
    id: '\d+'

# Authentication routes
login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

# Admin routes
admin_property_index:
  path: /admin/
  controller: App\Controller\Admin\AdminPropertyController::index

admin_property_save:
  path: /admin/property/save
  controller: App\Controller\Admin\AdminPropertyController::save

admin_property_update:
  path: /admin/property/{id}
  methods: [GET|POST]
  controller: App\Controller\Admin\AdminPropertyController::update
  requirements:
    id: '\d+'

admin_property_delete:
  path: /admin/property/{id}
  methods: [DELETE]
  controller: App\Controller\Admin\AdminPropertyController::delete
  requirements:
    id: '\d+'